name: Deploy Mandae PRD

on:
  push:
    branches:
      - production  # Agora só dispara quando você enviar para esta branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: 'github-deploy-mandae@sterlabs-mandae.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Deploy to Cloud Run (PRD)
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: mandae-prd
          region: us-central1
          source: .
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL_PRD }}
